### ISSUE TITLE
Followbot in ROS noetic

### ISSUE THREAD

**Issue by mariofaragalla** [TempleRAIL/followbot#2]
Hey, I was wondering if there is a new version with ROS noetic. Because I am trying to run the package in ros noetic but it is not working.

**Comment by zzuxzt** [comment]
Thank you for your interest in our work. I think it should work in Noetic version too if you installed the Turtlebot2 packages correctly. But I can check it out this weekend. By the way, can you share the specific error you were running with?

**Comment by mariofaragalla** [comment]
Thank you for your prompt response. I am more interested in Fred robot. However, following your instructions I installed turtlebot2 for ROS noetic from [here](https://gist.github.com/jeremyfix/0c5973aba508ee8b6e8d3c3077c6db1e) , but unfortunately I still had the following errors after this command `roslaunch followbot followbot_fred_robot.launch` was executed:

1. [ERROR] [1679868897.399552539]: No link elements found in urdf file.

2. [robot_state_publisher-8] process has died [pid 85595, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher __name:=robot_state_publisher __log:=/home/<username>/.ros/log/a3e24776-cc23-11ed-b20e-6d8971c7c8a2/robot_state_publisher-8.log].
log file: /home/<username>/.ros/log/a3e24776-cc23-11ed-b20e-6d8971c7c8a2/robot_state_publisher-8*.log

3. [ INFO] [1679868898.269947573]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
================================================================================REQUIRED process [follower_detector-9] has died!

4. Shutdown errors:
 * process[segment_mapper-12, pid 85636]: required SIGKILL. May still be running.


I believe that there might be other necessary packages for ros noetic. But I am not sure though.

**Comment by mariofaragalla** [comment]
I believe that error#1 might have to do sth. with using a new version of ROS as this [link](https://answers.ros.org/question/122021/xacro-problem-invalid-param-tag-cannot-load-command-parameter-robot_description/) suggests. But I can't totally fix it.

**Comment by zzuxzt** [comment]
Thanks for sharing. I just uploaded a new ROS Noetic version, please switch your branch to 'noetic'. The main problem is that ROS Noetic needs a different way of calling urdf files.

**Comment by mariofaragalla** [comment]
oh, thank you for the effort. 
Well, I replaced "robots", "src", "urdf" and "worlds" folders from the new branch 'noetic' in my old folder. Then I compiled using `catkin_make`. For fred robot, the simulation opened, however it is in a 'frozen' state. And I have the following error: 

[ERROR] [1679881483.587645, 2.004000]: bad callback: <bound method SegmentMapper.marker_callback of <__main__.SegmentMapper object at 0x7f1d863e0160>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/< username >//followbot/catkin_ws2/src/followbot/src/detector/segment_mapper.py", line 69, in marker_callback
    trans = self.tfBuffer.lookup_transform('odom', 'base_footprint', rospy.Time())
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/buffer.py", line 90, in lookup_transform
    return self.lookup_transform_core(target_frame, source_frame, time)
tf2.LookupException: "odom" passed to lookupTransform argument target_frame does not exist.

**Comment by zzuxzt** [comment]
Oh, strange. I have tested it in a Noetic environment and it works fine. Can you try again with the following command:
```Bash
cd catkin_ws/src/followbot
git checkout -b noetic
cd ../../
catkin_make
source devel/setup.sh
roslaunch followbot followbot_fred_robot.launch
```
If not, you can try commenting/removing the line 40-43 in the  'followbot_fred_robot.launch' file:  . Then, can you see  if it works?

**Comment by mariofaragalla** [comment]
I applied the commands that you wrote. but the same error arose. so I commented  the lines regarding the line following mapper , after that the error disappeared. But there is a minor detail I am no sure if it is important, the simulator runs with dark light ( please check the photo).

![Screenshot from 2023-03-27 08-48-45](https://user-images.githubusercontent.com/55330224/227862145-27b36a89-f863-4718-8b1f-043263cccb5f.png)

**Comment by zzuxzt** [comment]
This problem should be caused by your graphics card settings but does not affect the running. If your computer is running Gazebo with Intel HD Graphics, it may not be able to render lights and shadows. More details can be found [https://answers.gazebosim.org//question/21130/no-shadows-or-lights-in-gazebo/](url).
